---
# Configure Plone backups using Wheelbarrow from ToolShed

- name: create the backup directory
  ansible.builtin.file:
    path: "{{ toolshed_backup_plone_backup_dir }}"
    state: directory
    owner: "{{ toolshed_backup_plone_owner }}"
    group: "{{ toolshed_backup_plone_group }}"
    mode: 0775
  become: yes

- name: create the daily backup directory
  ansible.builtin.file:
    path: "{{ toolshed_backup_plone_backup_dir }}/daily"
    state: directory
    owner: "{{ toolshed_backup_plone_owner }}"
    group: "{{ toolshed_backup_plone_group }}"
    mode: 0775
  become: yes
  when: toolshed_backup_plone_daily > 0

- name: create the weekly backup directory
  ansible.builtin.file:
    path: "{{ toolshed_backup_plone_backup_dir }}/weekly"
    state: directory
    owner: "{{ toolshed_backup_plone_owner }}"
    group: "{{ toolshed_backup_plone_group }}"
    mode: 0775
  become: yes
  when: toolshed_backup_plone_weekly > 0

- name: create the monthly backup directory
  ansible.builtin.file:
    path: "{{ toolshed_backup_plone_backup_dir }}/monthly"
    state: directory
    owner: "{{ toolshed_backup_plone_owner }}"
    group: "{{ toolshed_backup_plone_group }}"
    mode: 0775
  become: yes
  when: toolshed_backup_plone_monthly > 0

- name: create the yearly backup directory
  ansible.builtin.file:
    path: "{{ toolshed_backup_plone_backup_dir }}/yearly"
    state: directory
    owner: "{{ toolshed_backup_plone_owner }}"
    group: "{{ toolshed_backup_plone_group }}"
    mode: 0775
  become: yes
  when: toolshed_backup_plone_yearly > 0


- name: create the backup script
  ansible.builtin.template:
    src: backupplone.sh.j2
    dest: "{{ toolshed_scripts_dir }}/{{ toolshed_backup_plone_script }}.sh"
    owner: "{{ devops_user|default(ansible_user) }}"
    group: "{{ devops_group|default('adm') }}"
    mode: 0775
  become: yes

- name: schedule the Cron task
  ansible.builtin.template:
    src: backupplone.cron.j2
    dest: "/etc/cron.d/{{ toolshed_backup_plone_script }}"
    owner: root
    group: root
    mode: 0644
  become: yes

